SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) TOTAL_SALES
FROM
(
SELECT B.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY, A.SALES, B.PRICE, DATE_FORMAT(A.SALES_DATE, "%Y-%m")
FROM BOOK_SALES A JOIN BOOK B JOIN AUTHOR C ON A.BOOK_ID = B.BOOK_ID AND B.AUTHOR_ID = C.AUTHOR_ID
WHERE DATE_FORMAT(A.SALES_DATE, "%Y-%m") = "2022-01"
) A
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC