SELECT B.FOOD_TYPE, B.REST_ID, B.REST_NAME, B.FAVORITES
FROM REST_INFO B
JOIN (
SELECT FOOD_TYPE, MAX(FAVORITES) AS MAXFA
FROM REST_INFO
GROUP BY FOOD_TYPE
) A ON B.FOOD_TYPE = A.FOOD_TYPE AND B.FAVORITES = A.MAXFA
ORDER BY B.FOOD_TYPE DESC