SELECT B.YEAR, B.MONTH, B.PURCHASED_USERS, ROUND(B.PURCHASED_USERS / A.USERS, 1) AS PUCHASED_RATIO
FROM
(
SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE YEAR(JOINED) = '2021'
) A,
(
SELECT YEAR(B.SALES_DATE) AS YEAR, MONTH(B.SALES_DATE) AS MONTH, COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS
FROM
(
SELECT USER_ID
FROM USER_INFO
WHERE YEAR(JOINED) = '2021'
) A INNER JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE)
) B
ORDER BY B.YEAR ASC, B.MONTH ASC