WITH TEMP_TABLE AS
(
    SELECT A.MEMBER_ID, A.MEMBER_NAME, B.REVIEW_TEXT, B.REVIEW_DATE
    FROM MEMBER_PROFILE A JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
)
SELECT B.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM
(
SELECT A1.MEMBER_ID
FROM
(
SELECT MEMBER_ID, COUNT(*) AS NUM
FROM TEMP_TABLE
GROUP BY MEMBER_ID
) A1 JOIN
(
SELECT MAX(NUM) AS MAX
FROM
(
SELECT MEMBER_ID, COUNT(*) AS NUM
FROM TEMP_TABLE
GROUP BY MEMBER_ID
) A1
) A2
WHERE A1.NUM = A2.MAX
) A JOIN TEMP_TABLE B ON A.MEMBER_ID = B.MEMBER_ID
ORDER BY B.REVIEW_DATE ASC, B.REVIEW_TEXT ASC