SELECT B.MONTH, A.CAR_ID, B.RECORDS
FROM
(
SELECT CAR_ID
FROM
(
SELECT CAR_ID, SUM(RECORDS) AS RECORDS
FROM
(
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE) = '2022' AND MONTH(START_DATE) IN('8', '9', '10')
GROUP BY MONTH(START_DATE), CAR_ID
) A
GROUP BY CAR_ID
) A
WHERE RECORDS >= 5
) A
JOIN
(
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE) = '2022' AND MONTH(START_DATE) IN('8', '9', '10')
GROUP BY MONTH(START_DATE), CAR_ID
) B ON A.CAR_ID = B.CAR_ID
ORDER BY B.MONTH ASC, A.CAR_ID DESC